export const ADD_SECTION = "ADD_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const CLEAR_ALL = "CLEAR_ALL";
export const UPDATE_CURRENT_COURSE = "UPDATE_CURRENT_COURSE";
export const CLEAR_CURRENT_COURSE = "CLEAR_CURRENT_COURSE";
export const NULLIFY_ID = "NULLIFY_ID";

export const SAVE_TIMETABLE = "SAVE_TIMETABLE";
export const EDIT_TIMETABLE = "EDIT_TIMETABLE";

export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAIL = "SUBMIT_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const UPDATE_INFO = "UPDATE_INFO";
export const USER_LOADED = "USER_LOADED";
export const NO_USER = "NO_USER";


export const OPEN_ALERT_DIALOG = "OPEN_ALERT_DIALOG";
export const CLOSE_ALERT_DIALOG = "CLOSE_ALERT_DIALOG";

export const OPEN_SAVE_ALERT = "OPEN_SAVE_ALERT";
export const CLOSE_SAVE_ALERT = "CLOSE_SAVE_ALERT";
