export const ADD_SECTION = "ADD_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const CLEAR_ALL = "CLEAR_ALL";
export const UPDATE_CURRENT_COURSE = "UPDATE_CURRENT_COURSE";
export const CLEAR_CURRENT_COURSE = "CLEAR_CURRENT_COURSE";

export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAIL = "SUBMIT_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
