export const ADD_SECTION = "ADD_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const CLEAR_ALL = "CLEAR_ALL";
export const UPDATE_CURRENT_COURSE = "UPDATE_CURRENT_COURSE";
export const CLEAR_CURRENT_COURSE = "CLEAR_CURRENT_COURSE";
